server:
  port: ${SERVER_PORT:8888}

spring:
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/irkan/ms-app.git
            search-paths:
              - "ms-config-properties/{profile}"
            username: irkan
            password: Irk@n19890925
        bootstrap: true
        git:
          order: 1


management:
  server:
    port: ${SERVER_PORT:9999}
  metrics:
    enable:
      all: true
      jvm: true
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: ALWAYS

data:
  key2: ${data.key}




