spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:/Users/user/IdeaProjects/ms-app/ms-config-properties/{profile},
            file:/Users/user/IdeaProjects/ms-app/ms-config-properties/global/{profile}
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/irkan/ms-app
          search-paths:
            - "ms-config-properties/{profile}"
            - "ms-config-properties/global/{profile}"
