info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account:
      path: /user/**
      serviceId: account-service
    customer:
      path: /customer/**
      serviceId: customer-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
    registerWithEureka: false

server:
  port: 8765

sso:
  client:
    accessTokenUri: http://localhost:8765/api/oauth/token
    userAuthorizationUri: http://localhost:8765/api/oauth/authorize
    clientId: clientIdMock
    clientSecret: clientSecretMock
  resource:
    userInfoUri: http://localhost:8765/api/resource/rest/me