server:
  port: ${SERVER_PORT:8500}
  servlet:
    context-path: /eureka

spring:
  application:
    name: ms-eureka
  profiles:
    active: ${PROFILE:DEV}
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  server:
    port: ${SERVER_PORT:9000}
  metrics:
    enable:
      all: true
      jvm: true
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: ALWAYS

eureka:
  server:
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:${server.port}/eureka/}